# Generated by Django 4.2.16 on 2024-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargeneration',
            name='model',
        ),
        migrations.AddField(
            model_name='model',
            name='car_generation',
            field=models.ManyToManyField(to='car.cargeneration'),
        ),
    ]
