# Generated by Django 4.2.16 on 2024-12-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_cargeneration_model_model_car_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_car_images/'),
        ),
    ]
